-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 12:48:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb_appointment` ;
DROP SCHEMA IF EXISTS `mydb_queue` ;
DROP SCHEMA IF EXISTS `mydb_service` ;
DROP SCHEMA IF EXISTS `mydb_shop` ;
DROP SCHEMA IF EXISTS `mydb_telegram_bot` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_appointment` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_queue` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_service` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_shop` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_shop_user` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_telegram_bot` DEFAULT CHARACTER SET utf8 ;
CREATE SCHEMA IF NOT EXISTS `mydb_user` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb_appointment`.`appointment` ;

CREATE TABLE IF NOT EXISTS `mydb_appointment`.`appointment` (
  `apt_id` INT NOT NULL AUTO_INCREMENT,
  `date_time` VARCHAR(256) NOT NULL,
  `duration` INT NOT NULL,
  `user_phone_number` INT NOT NULL,
  `vendor_confirm` TINYINT NOT NULL,
  `service_service_id` INT NOT NULL,
  `shop_shop_id` INT NOT NULL,
  PRIMARY KEY (`apt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb_queue`.`queue` ;

CREATE TABLE IF NOT EXISTS `mydb_queue`.`queue` (
  `queue_id` INT NOT NULL AUTO_INCREMENT,
  `queue_number` VARCHAR(45) NOT NULL,
  `is_done` TINYINT NOT NULL,
  `time_created` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `shop_shop_id` INT NOT NULL,
  `is_alert` TINYINT NOT NULL DEFAULT 0,
  `acknowledge` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`queue_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb_service`.`service` ;

CREATE TABLE IF NOT EXISTS `mydb_service`.`service` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `price` FLOAT NOT NULL,
  `shop_shop_id` INT NOT NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb_shop`.`shop` ;

CREATE TABLE IF NOT EXISTS `mydb_shop`.`shop` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `bot_id` VARCHAR(45) NOT NULL,
  `shop_url` VARCHAR(256) NOT NULL,
  `tele_url` VARCHAR(256) NOT NULL,
  `telegram_bot_bot_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`telegram_bot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb_telegram_bot`.`telegram_bot` ;

CREATE TABLE IF NOT EXISTS `mydb_telegram_bot`.`telegram_bot` (
  `bot_id` INT NOT NULL,
  `chat.id` JSON NOT NULL,
  PRIMARY KEY (`bot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Insert data into `mydb`.`appointment`
-- -----------------------------------------------------
INSERT INTO `mydb_appointment`.`appointment` (`apt_id`, `date_time`, `duration`, `user_phone_number`, `vendor_confirm`, `service_service_id`, `shop_shop_id`) 
VALUES (NULL, '2022-12-25 09:00:00', '20', '97624648', '0', '1', '1'),
(NULL, '2022-12-25 09:30:00', '20', '97729911', '0', '1', '1'),
(NULL, '2022-12-26 10:00:00', '120', '97624648', '0', '2', '1'),
(NULL, '2022-12-26 07:00:00', '120', '97729911', '0', '3', '1');

-- -----------------------------------------------------
-- Insert data into `mydb`.`queue`
-- -----------------------------------------------------
INSERT INTO `mydb_queue`.`queue` (`queue_id`, `queue_number`, `is_done`, `time_created`, `phone_number`, `shop_shop_id`, `is_alert`, `acknowledge`) 
VALUES (NULL, 'ESDShop1-1', '0', '2022-12-25 09:30:00', '86661340', '1', '0', '0');

-- -----------------------------------------------------
-- Insert data into `mydb`.`service`
-- -----------------------------------------------------
INSERT INTO `mydb_service`.`service` (`service_id`, `name`, `description`, `price`, `shop_shop_id`, `duration`) 
VALUES  ('1', 'Normal Haircut', 'Basic cut for all lengths', '15', '1', '20'),
('2', 'Perm hair', 'Newest Japanese Perm', '100', '1', '120'),
('3', 'Dye hair', 'Any basic dyeing without mixing', '70', '1', '120');

-- -----------------------------------------------------
-- Insert data into `mydb`.`shop`
-- -----------------------------------------------------
INSERT INTO `mydb_shop`.`shop` (`shop_id`, `name`, `location`, `bot_id`, `shop_url`, `tele_url`, `telegram_bot_bot_id`) 
VALUES ('1', "Jason\'s Hair Studio", 'Bencoolen', '1', "http://localhost:3000", "https://t.me/ESDg3t1_Queue_bot", '1');

-- -----------------------------------------------------
-- Insert data into `mydb`.`telegram_bot`
-- -----------------------------------------------------
INSERT INTO `mydb_telegram_bot`.`telegram_bot` (`bot_id`, `chat.id`) 
VALUES ('1', JSON_OBJECT("chat_ids", ''));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
